### ISSUE TITLE
"The file size exceeds the limitation set for your server" - on Onlyoffice SNAP version with Nextcloud.

### ISSUE THREAD

**Issue by nicemicro** [ONLYOFFICE/snap-documentserver#111]
I've seen issues opened concerning this problem with different versions of the Onlyoffice document server, such as https://github.com/ONLYOFFICE/DocumentServer/issues/1299, https://github.com/ONLYOFFICE/DocumentServer/issues/685 and https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/354.

However, as I have installed Onlyoffice on my server using the Snap package provided by the snap store, there is no `/etc/onlyoffice` directory on my system. I am aware of the `sudo snap set onlyoffice-ds` command which I used to set up the "secret" and the ports required, but I'm not sure if that can be applied on my current situation, and I also have not found any documentation on how to manage that part of the configuration on a server installed from Snap.

Thank you in advance for pointing me towards any resources regarding the issue.

**Comment by igwyd** [comment]
Hello @nicemicro, we haven't command to change this parameter, but you can change it in the snap config directory here ```/var/snap/onlyoffice-ds/current/etc/onlyoffice/```

**Comment by nicemicro** [comment]
@igwyd Thank you for the help!
I could find the `onlyoffice/documentserver/default.json` file, which I have changed according to [this closed issue](https://github.com/ONLYOFFICE/CommunityServer/issues/183), however, I haven't found `var/www/onlyoffice/WebStudio/web.appsettings.config` in the snap directory, so I couldn't overcome the "file size exceeds limitation" issue.

**Comment by igwyd** [comment]
You also need just restart the onlyoffice ```sudo snap restart onlyoffice-ds```. 
```web.appsettings.config``` this config in the ONLYOFFICE CommunityServer, not in the ONLYOFFICE documentserver.

**Comment by igwyd** [comment]
You did everything right. Old file won't open, re-upload it.

**Comment by igwyd** [comment]
So that the changes are not reset after update, you need to move them to ```/var/snap/onlyoffice-ds/current/etc/onlyoffice/documentserver/local.json``` in the same directive. Read more [here](https://api.onlyoffice.com/editors/faq/general).

**Comment by nicemicro** [comment]
Thank you for the kind help!
