### ISSUE TITLE
ONLYOFFICE cannot be reached. Please contact admin

### ISSUE THREAD

**Issue by gnosisd** [ONLYOFFICE/snap-documentserver#121]
so with snapd all is good i can as admin use onlyoffice but users when try to open a file the get the message ONLYOFFICE cannot be reached. Please contact admin
so what do i have to change here for users to be able to use onlyoffice as well???

thanks

**Comment by igwyd** [comment]
Hello @gnosisd, sorry for the late reply. What integration are you using? For example with Nexcloud - [You need an instance of ONLYOFFICE Docs that is resolvable and connectable both from Nextcloud and any end clients](https://helpcenter.onlyoffice.com/integration/gettingstarted-nextcloud.aspx#Requirements_block).

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
