### ISSUE TITLE
how to enable wopi?

### ISSUE THREAD

**Issue by cethink** [ONLYOFFICE/snap-documentserver#137]
> Before you get started with a demo sample of ONLYOFFICE Docs, please enable the WOPI protocol.
Set the wopi.enable parameter in the Document Server configuration file to true and restart ONLYOFFICE Docs.

I tried everything, all failed :(

**Comment by igwyd** [comment]
Hello @cethink, change ```wopi.enable:falce``` to ```wopi.enable:falce``` in the ```/var/snap/onlyoffice-ds/current/etc/onlyoffice/documentserver/default.json``` and restart the services ```sudo snap restart onlyoffice-ds```.

**Comment by cethink** [comment]
@igwyd thanks, I have tried, it doesn't work

**Comment by igwyd** [comment]
I did it right now on Ubuntu 20.04 server and it's work. Remove onlyoffice-ds with ```sudo snap remove --purge onlyoffice-ds``` and try again. How OS do you using, i will check.

**Comment by cethink** [comment]
The newest Almalinux, thanks.

**Comment by igwyd** [comment]
I checked it on Almalinux 9.3 - 5.14.0-362.8.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 7 14:54:22 EST 2023 x86_64 x86_64 x86_64 GNU/Linux and wopi enabling work same as i writed in my [previos post](https://github.com/ONLYOFFICE/snap-documentserver/issues/137#issuecomment-1805471707). Could you try againg on clean updated server?

**Comment by cethink** [comment]
@igwyd Ok.

**Comment by cethink** [comment]
it's stuck!
```
[root@alma ~]# snap install onlyoffice-ds
error: cannot perform the following tasks:
- Run install hook of "onlyoffice-ds" snap if present (run hook "install":
-----
Update plugins ...
------------------------------------------------------------------------------------

<exceeded maximum runtime of 10m0s>
-----)
```
I use proxy with this, seems useless
```
snap set system proxy.https="http://127.0.0.1:7890"
snap set system proxy.http="http://127.0.0.1:7890"
```
Last time the installation was successful, I tried several times.

**Comment by cethink** [comment]
@igwyd Never mind, I give up :)
