### ISSUE TITLE
Please support certificates over letsencrypt. Would make the configuration much easier

### ISSUE THREAD

**Issue by szaimen** [ONLYOFFICE/snap-documentserver#17]
You could have a look at the nextcloud-snap how they implemented this.

**Comment by BMTTeam** [comment]
Since this is enhancement from 2019, are there any tips or some workaround in order to make it work with LE?

**Comment by igwyd** [comment]
Hello @szaimen, sorry for the late reply. Onlyoffice-documentserver can work with LE certificates. You can get them and add to the server like [here](ubuntu-test). Or do you mean something else?

**Comment by igwyd** [comment]
It's fixed many times ago, at https://github.com/ONLYOFFICE/snap-documentserver/commit/8862ff1a077fd1f8a5dbe8fd6b3a3db4281d8bc7, i think we will close this as fixed.
