### ISSUE TITLE
Use `sudo` at all places or not use at all commands

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/snap-documentserver#18]
In https://github.com/ONLYOFFICE/snap-documentserver/blob/master/README.md
part of commands for `snap` uses `sudo` (`sudo snap set onlyoffice-ds onlyoffice.ds-port=8888
`), part use not (`snap remove onlyoffice-ds`), I think they should all have consistent style

**Comment by agolybev** [comment]
@Igor-Pigalitsyn, use '#' for command running under root and `$` for a normal user command.
