### ISSUE TITLE
`Something went wrong during installation` on centos 7

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/snap-documentserver#19]
1. Start centos 7
2. Install snap via https://snapcraft.io/docs/installing-snap-on-centos
3. `sudo snap install onlyoffice-ds --beta`
4. Open localhost

`Something went wrong during installation`

![image](https://user-images.githubusercontent.com/668524/66742342-1cec8d00-ee80-11e9-954e-34b1d1c932b4.png)

Tested on:
CentOS Linux release 7.7.1908 (Core)
snap: onlyoffice-ds  5.4.0-7
snapd 2.42-4992

**Comment by NorseGaud** [comment]
Same

**Comment by Igor-Pigalitsyn** [comment]
Hi, @NorseGaud!
We fixed this problem. Please make sure you are using the latest version of the stable package channel. Give more information if the problem repeat again.

**Comment by blackerking** [comment]
Rabitmq makes this entrys:
`
=INFO REPORT==== 3-Mar-2020::13:53:41 ===
ERROR: "Free disk space monitor encountered an error (e.g. failed to parse output from OS tools): ~p, retries left: ~s~n" - [{{'EXIT',
                                                                                                                               {unparseable,
                                                                                                                                "/bin/sh: 1: /bin/df: Permission denied\n"}},
                                                                                                                              16521142272},
                                                                                                                             1]

`

**Comment by franciscopaniskaseker** [comment]
@blackerking probably your OS is blocking some commands. Are you using selinux or apparmor? I saw it happening today with one ubuntu 20.04.1 server using onlyoffice under snap. The app armor without anyone touch started to block all commands that come from that snap installation.

**Comment by blackerking** [comment]
Maybe but I have to say that I don't use this anymore. Was shifting to docker image. Works like a charm.

**Comment by igwyd** [comment]
Helllo @All, support stopped for the Centos 7 at the moment.
