### ISSUE TITLE
Something went wrong during installation Make sure that you have followed the installation instructions

### ISSUE THREAD

**Issue by guoguoguilai** [ONLYOFFICE/snap-documentserver#25]
I have tried many times but failed. 
![image](https://user-images.githubusercontent.com/47267017/68122728-f59c5380-ff45-11e9-8689-faa469f0a77b.png)

#14 #19 
I also used the latest "stable:    5.4.0 2019-10-28 (10) 595MB -",but it turns to be useless.
I alse tried  ubuntu16.04,ubuntu18.04 on new EC2 ,which has no mysql and appche, and nginx.

**Comment by igwyd** [comment]
Hello @guoguoguilai, sorry for the late reply, since 2019 we realeased many versions and fix mane bugs, could you try install again the actual version?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
