### ISSUE TITLE
Save as PDF doesn't output text from Presentation Slides

### ISSUE THREAD

**Issue by duderino416** [ONLYOFFICE/snap-documentserver#29]
I want to report a bug.

Presentations doesn't save text from slides onto pages when saved as PDF.

Create a slide with text and images on it using the provided templates, notice lack of text in resulting PDF. 

Expect text to be saved into PDF as text. Not present or visible at all.

Unaware if it worked in previous versions. 

**DocumentServer version:**
Community Edition Installed via Snap 5.4.0

**Operating System:**
Ubuntu Server 18.04 - Integrated with Nextcloud.

**Browser version:**
Windows Google Chrome Version 79.0.3945.79

**Comment by Rita-Bubnova** [comment]
@duderino416, we were able to reproduce your problem. @agolybev take a look.

**Comment by duderino416** [comment]
Thank you for the speedy progress update.

**Comment by duderino416** [comment]
Any idea if this will be fixed in the next update?

**Comment by wes3161** [comment]
I am also experiencing this problem for what its worth. Is there  a fix in the works as otherwise I might just switch back to the docker container :(

**Comment by duderino416** [comment]
I am still experiencing this issue in 5.4.2 2020-01-17

**Comment by romandemidov** [comment]
Fixed by https://github.com/ONLYOFFICE/snap-documentserver/commit/bae94cf54d1918333a9298b6368d82c0718bae82
