### ISSUE TITLE
Changing default settings when creating a new document

### ISSUE THREAD

**Issue by myopenflixr** [ONLYOFFICE/snap-documentserver#30]
Hello,

This is more of a question or a Feature Request that an issue.

I was wondering if it is possible to change some of the "defaults" when creating a new document?

Specifically, I would like to change the following defaults:
- Default Font from Arial to something else
- Default Font Size from 11 to 12
- Default Unit of Measurement from Centimeter to Inch
- Default Page Size from A4 (8.27" x 11.69") to US Letter (8.5" x 11")

Is this possible with the Snap version?

Please advise!

Thanks,
Mike

**Comment by igwyd** [comment]
Hello @myopenflixr, the onlyoffice-documentserver doesn't create files when you integrate it with your app, you can create file with your font and stile and choose it https://api.onlyoffice.com/editors/config/document#url

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
