### ISSUE TITLE
Spreadsheet changes not save

### ISSUE THREAD

**Issue by spardahk** [ONLYOFFICE/snap-documentserver#32]
Hello, I installed Onlyoffice 5.4 and Nextcloud 16.0.5 installed on Ubuntu 18.04.3 using Snap.
After doing some setup, changes done for word and powerpoint are saved but not spreadsheet.

There is this error in the converter out.log after I edit a spreadsheet, but none if I edit word or powerpoint.

```
[2020-01-09T12:14:40.552] [ERROR] nodeJS - stderr (id=278330130_2252):change_code: Ma.KRd(z,Ea.TP,Ea.$ba,Ea.V4,Ea.t2b,Ea.G7)}AscFonts.hV=!1;c=this.jVa();a.Asc.editor.r3a(c,function(){if(e.FO.wk.YA)for(var a in y)if(vc(y[a])&&vc(y[a].Bg)&&vc(y[a].Bg.controller)){var c=y[a].Bg.m8e();c&&(c.Ua&&AscCommon.Rd.u5(c.Ua),c.xa&&AscCommon.Rd.u5(c.xa),c.ya&&AscCommon.Rd.u5(c.ya));y[a].Bg.Rdf()}Qe.c0b=!0;Qe.G_b=!0;Ma.pcd(null,z,!1);pb.Gt();e.FT=!1;e.jFc=e.V8a();null!=d&&d()})}else null!=d&&d()};Ua.prototype.FIf=function(c,d,e){if(null!=d){this.FT=!0;if(null==c){c=a.Asc.editor.ud.oba;for(var h in c)vc(c[h])&&
change: Uncaught TypeError: Cannot read property 'oba' of null
DoctRenderer:<result><error index="-2" /></result>
```

**Comment by akoyaxd** [comment]
Hey, I have the exact same issue!

I tested:
latest/stable | 5.4.0 | 23 October 2019
latest/edge | 5.4.2 | 17 January 2020

Direct install: There wasn't any problem with saving spreadsheets there.

**Comment by CacheMinimal** [comment]
I have the same issue on Ubuntu 18.04 LTS server running 5.4.0 stable snap.  The only possibly related log entries I can find are:

```
Feb  7 19:07:49 woody kernel: [873308.685265] audit: type=1400 audit(1581102469.677:466): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=32104 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:07:49 woody kernel: [873308.685272] audit: type=1400 audit(1581102469.677:467): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=32104 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:07:49 woody kernel: [873308.685743] audit: type=1400 audit(1581102469.677:468): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=32104 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:07:49 woody kernel: [873308.685750] audit: type=1400 audit(1581102469.677:469): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=32104 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:08:29 woody kernel: [873348.430827] audit: type=1400 audit(1581102509.424:470): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=32232 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:08:29 woody kernel: [873348.430832] audit: type=1400 audit(1581102509.424:471): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=32232 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:08:29 woody kernel: [873348.431292] audit: type=1400 audit(1581102509.424:472): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=32232 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:08:29 woody kernel: [873348.431296] audit: type=1400 audit(1581102509.424:473): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=32232 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:15:15 woody kernel: [873754.851171] audit: type=1400 audit(1581102915.833:474): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=582 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:15:15 woody kernel: [873754.851185] audit: type=1400 audit(1581102915.833:475): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=582 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:15:15 woody kernel: [873754.851551] audit: type=1400 audit(1581102915.833:476): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=582 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  7 19:15:15 woody kernel: [873754.851573] audit: type=1400 audit(1581102915.833:477): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=582 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by akoyaxd** [comment]
> I have the same issue on Ubuntu 18.04 LTS server running 5.4.0 stable snap. The only possibly related log entries I can find are:
> 
> ```
> Feb  7 19:07:49 woody kernel: [873308.685265] audit: type=1400 audit(1581102469.677:466): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=32104 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:07:49 woody kernel: [873308.685272] audit: type=1400 audit(1581102469.677:467): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=32104 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:07:49 woody kernel: [873308.685743] audit: type=1400 audit(1581102469.677:468): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=32104 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:07:49 woody kernel: [873308.685750] audit: type=1400 audit(1581102469.677:469): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=32104 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:08:29 woody kernel: [873348.430827] audit: type=1400 audit(1581102509.424:470): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=32232 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:08:29 woody kernel: [873348.430832] audit: type=1400 audit(1581102509.424:471): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=32232 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:08:29 woody kernel: [873348.431292] audit: type=1400 audit(1581102509.424:472): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=32232 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:08:29 woody kernel: [873348.431296] audit: type=1400 audit(1581102509.424:473): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=32232 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:15:15 woody kernel: [873754.851171] audit: type=1400 audit(1581102915.833:474): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=582 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:15:15 woody kernel: [873754.851185] audit: type=1400 audit(1581102915.833:475): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25" pid=582 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:15:15 woody kernel: [873754.851551] audit: type=1400 audit(1581102915.833:476): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=582 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> Feb  7 19:15:15 woody kernel: [873754.851573] audit: type=1400 audit(1581102915.833:477): apparmor="DENIED" operation="open" profile="snap.onlyoffice-ds.documentserver" name="/snap/core18/1668/lib/x86_64-linux-gnu/libgcc_s.so.1" pid=582 comm="x2t" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
> ```

I am having the same log entries.  Did you try the edge Version? (5.4.2)
On that Version they disappear. But Spreadcheats still don't get saved.

**Comment by CacheMinimal** [comment]
> I am having the same log entries. Did you try the edge Version? (5.4.2)
> On that Version they disappear. But Spreadcheats still don't get saved.

Afraid I didn't try the edge version as others had previously indicated no improvement.  I've defected to the Docker image for now and everything works just beautifully on Ubuntu 18.04 LTS server.
