### ISSUE TITLE
JSON Web Token

### ISSUE THREAD

**Issue by Sys-Admin889** [ONLYOFFICE/snap-documentserver#34]
How to enable JWT settings and edit it for ONLYOFFICE Document Server version 5.5 installed on Ubuntu 18.4 LTS?

![Capture2](https://user-images.githubusercontent.com/59320357/76799994-5896d480-67db-11ea-8992-2227dd3c5b10.JPG)

The problem is that I can't find default.json file in /etc/onlyoffice/documentserver/ or other paths.

**Comment by igwyd** [comment]
Hello @Sys-Admin889, sorry for the late reply. You can edit JWT settings as described https://github.com/ONLYOFFICE/snap-documentserver#json-web-token. Config file default.json locate here ```/var/snap/onlyoffice-ds/current/etc/onlyoffice/documentserver/default.json```

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
