### ISSUE TITLE
Changing the port for SSL doesn't work.

### ISSUE THREAD

**Issue by piiskop** [ONLYOFFICE/snap-documentserver#40]
I did everything told in instructions and please have a look at my last commands and results:
"kalmer@test:~$ sudo snap set onlyoffice-ds onlyoffice.ds-ssl-port=270
kalmer@test:~$ sudo netstat -plunt|grep :270
kalmer@test:~$ "
As we see, nothing runs on port 270 after changing the port.

**Comment by igwyd** [comment]
Hello @piiskop, sorry for the late reply, i checked and now it work, since 2020 we realeased many versions and fix many bugs, could you try install again the actual version?

**Comment by piiskop** [comment]
I do not want to waste my time on ONLYOFFICE anymore as I moved on to RStudio Server and am using _LibreOffice_ offline. ONLYOFFICE is currently running in _docker_ for legacy purposes.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
