### ISSUE TITLE
Changing the http port does not work with the latest version

### ISSUE THREAD

**Issue by Axelen123** [ONLYOFFICE/snap-documentserver#43]
snap version: 5.6.5 (from edge channel).

I tried to change the http port using the instructions in the README. It restarts nginx but it still listens on port 80.

**Comment by GyozaGuy** [comment]
I am seeing this same issue with version 5.4.0 on Ubuntu server 20.04.

**Comment by igwyd** [comment]
Hello @Axelen123, sorry for the late reply, now it work, this is [guide](https://github.com/ONLYOFFICE/snap-documentserver#running-onlyoffice-document-server-on-different-port). We realeased many versions and fix many bugs, could you try install again the actual version?

**Comment by Axelen123** [comment]
I migrated away from snap a long time ago in favor of docker, so I can't really test this myself.

This issue can be closed if the problem has been resolved

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
