### ISSUE TITLE
Welcome page on main page

### ISSUE THREAD

**Issue by kavalun** [ONLYOFFICE/snap-documentserver#45]
Install from snap: sudo snap install onlyoffice-ds. All fine, but after install i open page 192.168.1.10 and have redirect on 192.168.1.10/welcome/ and nothing happened next

**Comment by igwyd** [comment]
Hello @kavalun, sorry for the late reply, what do you expect?

**Comment by derosieres** [comment]
Hello, same thing, after installing and displaying the forms, I don't understand how to connect to the server on the application

**Comment by igwyd** [comment]
Hello @derosieres, how integration do you use? We have many [guides](https://helpcenter.onlyoffice.com/integration.aspx), in our helpcenter portal.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
