### ISSUE TITLE
Snap auto update broke configuration

### ISSUE THREAD

**Issue by Ultraspider** [ONLYOFFICE/snap-documentserver#53]
Hello,

It seems that yesterday, onlyoffice-ds got updated automatically on my server.
`Done    yesterday at 17:34 CET  yesterday at 17:35 CET  Download snap "onlyoffice-ds" (25) from channel "latest/stable"`

the automatic restart was unable to perform due to nginx ports already in use.

The file /var/snap/onlyoffice-ds/25/etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl seems to ignore the ds-port settings

Also, I tried to find the recent changes to this file in this repository by searching for "#HTTP host for internal services" or "127.0.0.1" that I can see in the file on my server and it yields no results.

here is the relevant section of the file that is causing problem (and that I could not find in this repository):
```## Normal HTTP host
server {
  listen 0.0.0.0:80;
  listen [::]:80 default_server;
  server_name _;
  server_tokens off;

  ## Redirects all traffic to the HTTPS host
  root /nowhere; ## root doesn't have to be a valid path since we are redirecting
  rewrite ^ https://$host$request_uri? permanent;
}

#HTTP host for internal services
server {
  listen 127.0.0.1:80;
  listen [::1]:80;
  server_name localhost;
  server_tokens off;

  include /etc/nginx/includes/ds-common.conf;
  include /etc/nginx/includes/ds-docservice.conf;
}
```

I'm not familiar with snap release cycle so I'm maybe searching at the wrong place but something feels not right anyway.

**Comment by igwyd** [comment]
Hello @Ultraspider
To make the document server work, you need reinstall it, because after latest version the configuration has a lot of changes:
```
sudo snap remove --purge onlyoffice-ds
sudo snap install onlyoffice-ds
```

**Comment by Ultraspider** [comment]
Alright, thanks, I was able to redo the configuration (custom http and https ports and connect to removable-media) but I wasn't able to display the welcome page (502 Bad Gateway) until I add `::1 localhost` in my /etc/hosts file. Previous version of onlyoffice-ds was working well without it.

How can one be aware of having to do a full reinstall on update ? Auto update is on by default so I guess I'm not the only one who will face the issue.

**Comment by igwyd** [comment]
Thank you @Ultraspider
I can confirm - this is bug, issue 48500 in our private issue tracker.
