### ISSUE TITLE
Automatic update from 25 to 28 broke SSL configuration

### ISSUE THREAD

**Issue by Ultraspider** [ONLYOFFICE/snap-documentserver#57]
Hello,

After notification from the users that onlyoffice was unreachable, I noticed that the server was not listening on the SSL port anymore.

The folder /var/snap/onlyoffice-ds/25/var/www/onlyoffice/Data containing the certs folder with the SSL certificates is not present in /var/snap/onlyoffice-ds/28/var/www/onlyoffice/

The following commands were enough to solve the issue.
```
# cp -r /var/snap/onlyoffice-ds/25/var/www/onlyoffice/Data /var/snap/onlyoffice-ds/current/var/www/onlyoffice/
# snap restart onlyoffice-ds
```

**Comment by igwyd** [comment]
Thank you @Ultraspider
I can confirm - this is bug, issue 48670 in our private issue tracker.
