### ISSUE TITLE
Modifications are lost in documents.

### ISSUE THREAD

**Issue by Ultraspider** [ONLYOFFICE/snap-documentserver#59]
Hello,

Some of my users are reporting that they are losing changes that they made in documents. It seems to have started 6 days ago and I can see in the snapd logs that onlyoffice-ds was updated 6 days ago.

I haven't been able to reproduce the issue yet. I'm still investigating the issue. 

Do you have reports about that or do you know how the last update could maybe cause that ? Any clues could be helpful at this point. Sorry for the lack of info about this one. I'll update this issue if I find something.

**Comment by igwyd** [comment]
Hello @Ultraspider, sorry for the late reply. I have discovered that changes may be lost in the snap onlyoffice-documentserver during an upgrade to a new version. I confirm - this is bug issue #65140

**Comment by igwyd** [comment]
It's fixed at https://github.com/ONLYOFFICE/snap-documentserver/commit/a0842a277483d774971b19a02bbf4159da8a6606 and will be released in the next major release.

**Comment by igwyd** [comment]
Hello @Ultraspider, we released snap with the fix.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
