### ISSUE TITLE
What to do if I have SSL with letsencrypt?

### ISSUE THREAD

**Issue by PrzemekSkw** [ONLYOFFICE/snap-documentserver#64]
Hello, I have on my server already Traccar Server installed and I use No-ip and letsencrypt. I have files in 
```
/etc/letsencrypt/live/mydomainname.ddns.net/:
cert.pem  chain.pem  fullchain.pem  privkey.pem
```
Can I use this files or I have to generate new with openssl like in tutorial?
Regards.

**Comment by igwyd** [comment]
Hello @PrzemekSkw
Yes, you can use your certificates, for example:
1. Copy fullchain.pem and privkey.pem to /var/snap/onlyoffice-ds/current/var/www/onlyoffice/Data/certs/
2. Go to /var/snap/onlyoffice-ds/current/var/www/onlyoffice/Data/certs/ and rename  fullchain.pem -> onlyoffice.crt and privkey.pem -> onlyoffice.key
3. sudo snap restart onlyoffice-ds

**Comment by PrzemekSkw** [comment]
@igwyd Hi, I try Your way but don't work. I set port to 444 but cannot make it work. In my https://mydomain.ddns.net I have still Traccar server working.

Regards.
Przemek

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
