### ISSUE TITLE
Auto update broke service again.

### ISSUE THREAD

**Issue by Ultraspider** [ONLYOFFICE/snap-documentserver#65]
Hi,
Came back today to my user complaining that onlyoffice is down.

Here's the log of the machine

```
Mar 29 14:15:38 nextcloud systemd[1]: snap.onlyoffice-ds.nginx.service: Main process exited, code=exited, status=1/FAILURE
Mar 29 14:15:38 nextcloud systemd[1]: snap.onlyoffice-ds.nginx.service: Failed with result 'exit-code'.
Mar 29 14:15:39 nextcloud systemd[1]: snap.onlyoffice-ds.nginx.service: Service hold-off time over, scheduling restart.
Mar 29 14:15:39 nextcloud systemd[1]: snap.onlyoffice-ds.nginx.service: Scheduled restart job, restart counter is at 235.
Mar 29 14:15:39 nextcloud systemd[1]: Stopped Service for snap application onlyoffice-ds.nginx.
Mar 29 14:15:39 nextcloud systemd[1]: Started Service for snap application onlyoffice-ds.nginx.
Mar 29 14:15:39 nextcloud onlyoffice-ds.nginx[4706]: nginx: [emerg] bind() to 127.0.0.1:80 failed (98: Address already in use)
Mar 29 14:15:39 nextcloud onlyoffice-ds.nginx[4706]: nginx: [emerg] bind() to [::1]:80 failed (98: Address already in use)
```

Nowhere is specified port 80 in the configuration :
```
root@nextcloud:/var/log# snap get onlyoffice-ds onlyoffice.ds-port
8888
root@nextcloud:/var/log# snap get onlyoffice-ds onlyoffice.ds-ssl-port
444
```

Can you tell me why is this happening ?

**Comment by Ultraspider** [comment]
The problem seems to lie in the file /var/snap/onlyoffice-ds/25/etc/onlyoffice/documentserver/nginx/ds-ssl.conf.tmpl

```
#HTTP host for internal services
server {
  listen 127.0.0.1:80;
  listen [::1]:80;
```

I changed the port to 8889 and the service restarted correctly. I don't know what this vhost is for, as onlyoffice seems to be working normally with the arbitrary port I set and I guess no other component is aware of that port.

**Comment by fabiobulgarella** [comment]
Same problem for me, we need an additional snap setting to change that binding too

**Comment by igwyd** [comment]
Thank you @Ultraspider
I can confirm - this is bug, issue 49352 in our private issue tracker.

**Comment by Ultraspider** [comment]
Auto update happened again yesterday 
```Apr  1 19:33 current -> 38```
The issue is still present on version 38. I had to manually change the file mentioned above so the processes could start normally.
