### ISSUE TITLE
OnlyOffice 6.3.0 snap wont work with NC 21 + OO 7.0.2.

### ISSUE THREAD

**Issue by scornet256** [ONLYOFFICE/snap-documentserver#71]
**Do you want to request a *feature* or report a *bug*?**
Bug report ...

**What is the current behavior?**
Trows error and Nextcloud 21.0.1 with OnlyOffice Plugin version 7.0.2 will not save and use OnlyOffice 6.3.0 provided from a snap, where it did use to work with 6.2.2.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/41006695/119674648-a924ab80-be3c-11eb-9a41-e847bb011102.png)

**What is the expected behavior?**
Settings saved and a usable OnlyOffice Document Server.

**Did this work in previous versions of DocumentServer?**
Yes, after snap revert onlyoffice-ds to 6.2.2 all works fine.

**DocumentServer version:**
6.3.0 - snap

**Operating System:**
Ubuntu 20.04 LTS

**Browser version:**
Any ...

With both versions I've enabled the JWT settings using these commands:
```
snap set onlyoffice-ds onlyoffice.jwt-enabled=true
snap set onlyoffice-ds onlyoffice.jwt-secret=supersecretstring
```

**Comment by ShockwaveNN** [comment]
Seems this is snap related problem moving it to correct repo

@igwyd please take a look

**Comment by scornet256** [comment]
Sorry and thanks @ShockwaveNN ... :)

**Comment by igwyd** [comment]
hello, @scornet256.
I can confirm - this is bug, issue 50622 in our private issue tracker.
But there is a workaround:
1. Upgrade onlyoffice-ds
```
snap refresh --channel=stable onlyoffice-ds
```
2. Disable JWT and change secret string to "secret"
```
snap set onlyoffice-ds onlyoffice.jwt-enabled=false 
snap set onlyoffice-ds onlyoffice.jwt-secret=secret
```
3. Enable JWT again with your original key
```
snap set onlyoffice-ds onlyoffice.jwt-enabled=true 
snap set onlyoffice-ds onlyoffice.jwt-secret=supersecretstring

**Comment by scornet256** [comment]
@igwyd Thank you! The workaround works indeed ... :blush:
