### ISSUE TITLE
run hook "install" exceeded maximum runtime of 10min0s

### ISSUE THREAD

**Issue by King-GO** [ONLYOFFICE/snap-documentserver#87]
Try to disable the Community Document Server and use onlyoffice-dc instead.
snap install onlyoffice-ds
get error
- Run install hook of "onlyoffice-ds" snap if present (run hook "install"; exceeded maximum runtime of 10min0s)

sanp version
sanp 2.53.4
snapd 2.53.4
series 16
ubuntu 20.04
kernel 5.4.0-65-generic

**Comment by igwyd** [comment]
Hello @King-GO, do you mean this https://apps.nextcloud.com/apps/documentserver_community Community Document Server?

**Comment by King-GO** [comment]
Yes

**Comment by igwyd** [comment]
I have verified, the ONLYOFFICE snap installation is working on clean server. [Community Document Server](https://apps.nextcloud.com/apps/documentserver_community) is not our application and we do not support it. You should contact its developer to find out how to properly disable or remove it. I guess it interferes with the installation, but I can't help you with that.

**Comment by King-GO** [comment]
Yes, i KNOW that the community document server has tons of outstanding issues and has not been fixed yet (like [this ](https://github.com/nextcloud/documentserver_community/issues/100)) , so I've tried to find alternatives to get better integration with Nextcloud-Snap, [onlyoffice connector ](https://apps.nextcloud.com/apps/onlyoffice) and onlyoffice-document-server in one machine, but without success. Do you have any recommendations?

**Comment by ShockwaveNN** [comment]
We always advise to use our official Docker version of DocumentServer - it has most configs and most easier to use

**Comment by igwyd** [comment]
@King-GO nextcloud and onlyoffice-ds uses 80 port by default in snap, it leads to conflict. You need to change this port for one of your applications, for example in snap onlyoffice-ds you can do it like [this](https://github.com/ONLYOFFICE/snap-documentserver#running-onlyoffice-document-server-on-different-port). 
And as @ShockwaveNN correctly noted, we recommend [docker](https://github.com/ONLYOFFICE/Docker-DocumentServer) as more stable and more configurable. We have ready solution with nexcloud in docker [here](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud).

**Comment by King-GO** [comment]
Currently, there are some difficulties migrating the existing setup to docker. 
Can I use docker-snap (which comes pre-installed in Ubuntu) for the onlyoffice-ds ? or need to remove it and install docker without snap?

**Comment by igwyd** [comment]
We have not tested the docker snap distribution, we recommend installing docker using the official documentation([for Ubuntu](https://docs.docker.com/engine/install/ubuntu/)). Dont forget change port like [this](https://github.com/ONLYOFFICE/Docker-DocumentServer#running-onlyoffice-document-server-on-different-port).

**Comment by Rita-Bubnova** [comment]
I'll close this issue. Feel free to comment or reopen it if you got further questions.
