### ISSUE TITLE
[Feature] Option to run on loopback

### ISSUE THREAD

**Issue by mwt** [ONLYOFFICE/snap-documentserver#88]
For security, I would like to run this only on the loopback interface. Can you add an option to change the interface?

**Comment by igwyd** [comment]
Hello @mwt, can you tell me for what you need document-server "on the loopback interface"? We have desktopeditors tо edit documents on one computer.
For understanding request, мaybe you know some other snap packages that have a similar feature.

**Comment by mwt** [comment]
If I run it on a server that serves php/cgi, those scripts can access the API. However, no other server can (as it is not public).

I use my firewall right now to block the port.

**Comment by igwyd** [comment]
I understand what you need, but still can't understand for what? Please describe in more detail. No one(except you) will can use documentserver on loopback interface.  
And you didn't answer, do you know an application that can do this?

**Comment by mwt** [comment]
I do not know of any application that cannot do this. Apache, Nginx, and Webmin, and Resilio are some examples. In fact, the onlyoffice document server does it by default when not using this snap (and even inside the snap to communicate with Nginx). Because this snap uses Nginx, this is a config change. I can do it and submit a pull if the feature is desirable.

If no one else can find any use for it, that is fine. I'll continue to use iptables to block this port. I just thought that this would be popular. There are probably many users listening on loopback, but they probably use docker or deb rather than this snap.

**Comment by igwyd** [comment]
Thank you, i created a enhancement bug 55491 in our private issue tracker.

**Comment by igwyd** [comment]
@mwt feature added https://github.com/ONLYOFFICE/snap-documentserver/commit/32518bdee71aa485492758dbf90789bfb13d0a16 you can set it https://github.com/ONLYOFFICE/snap-documentserver#set-document-server-to-run-on-loopback-interface

**Comment by ShockwaveNN** [comment]
I'll close this issue, but feel free to comment\reopen it if got any questions
