### ISSUE TITLE
mysql does not respect onlyoffice.db-port

### ISSUE THREAD

**Issue by ahcm** [ONLYOFFICE/snap-documentserver#89]
Setting onlyoffice.db-port does not have effect.
Since there is already another mysql running on 3306, it cannot start.
Snap 7.0.0.

**Comment by igwyd** [comment]
Hello, @ahcm 
Thank you for report.
I can confirm - this is bug, issue 55529 in our private issue tracker.

**Comment by igwyd** [comment]
It's fixed at:
https://github.com/ONLYOFFICE/snap-documentserver/commit/8be08f7b5768f798bc9aed17a836c30984880f43
And will be appear in the snap (probably build 66)

**Comment by igwyd** [comment]
@ahcm bug fixed and build released. You can check it.

**Comment by ahcm** [comment]
Yes, it's fixed.
