### ISSUE TITLE
How do I hide the welcome page?

### ISSUE THREAD

**Issue by EzequielBruni** [ONLYOFFICE/snap-documentserver#96]
I tried commenting out the relevant line of text in /var/snap/onlyoffice-ds/current/etc/onlyoffice/documentserver/nginx/includes/ds-docservice.conf. But when I restarted the whole snap package, the page was still there. I double checked the file, and the line is still commented out. So how do I turn it off?

**Comment by EzequielBruni** [comment]
Bonus question, where in the heck did you stick the fonts? I'd like to add some more...

**Comment by igwyd** [comment]
Hello @EzequielBruni you need also edit path in config files ```ds.conf.tmpl``` and ```ds-ssl.conf.tmpl```. Add **/var** in include path same this ```include /var/snap/onlyoffice-ds/current/etc/onlyoffice/documentserver/nginx/includes/ds-*.conf;``` and execute ```sudo snap restart onlyoffice-ds```.
I created issue 56746 in our private issue tracker for it behavior.

**Comment by igwyd** [comment]
As for the second question, script that generating fonts run during installation/updating onlyoffice-ds. To add a font copy it in /usr/share/fonts/ and reinstall/update snap onlyoffice-ds.

**Comment by igwyd** [comment]
It's fixed at: https://github.com/ONLYOFFICE/snap-documentserver/commit/7a3dcb362a28c6635aac40bb7003afb81db2b075
And will be released in the next release.

**Comment by EzequielBruni** [comment]
Thanks for the update!

**Comment by ShockwaveNN** [comment]
@EzequielBruni Thanks for closing this issue, seems I've forgot to do that
